name: build-dashboard
on:
  push:
    branches: ['gh-pages']
    paths: ['pr-status/**']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HAVE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN != '' }}
      HAVE_SAXON_LICENSE: ${{ secrets.SAXON_LICENSE != '' }}
      # There’s no particular reason why the TEST_REPOSITORY should be
      # a secret. This is the only way I can think of to initialize
      # a variable based on the repository that the action is running in,
      # rather than the *contents* of that repository.
      UPDATE_TESTS: ${{ secrets.TEST_REPOSITORY != '' && secrets.ACCESS_TOKEN != '' }}
      AUTODIFF: ${{ secrets.DIFFURI != '' && secrets.DIFFPW != '' }}
      PUBLISH_TESTS_FROM: "master"
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout the specifications
        uses: actions/checkout@v3

      - name: Build
        run: |
          ls -l

